export const en = {
  // Navbar
  "nav.home": "Home",
  "nav.templates": "Templates",
  "nav.pricing": "Pricing",
  "nav.login": "Login",
  "nav.signup": "Sign Up",

  // Footer
  "footer.description": "Create stunning portfolios for developers and designers with ease.",
  "footer.product": "Product",
  "footer.customers": "Customers",
  "footer.features": "Features",
  "footer.resources": "Resources",
  "footer.documentation": "Documentation",
  "footer.guides": "Guides",
  "footer.apiReference": "API Reference",
  "footer.blog": "Blog",
  "footer.company": "Company",
  "footer.about": "About",
  "footer.careers": "Careers",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.rights": "All rights reserved.",

  // Hero Section
  "hero.title": "Create your professional",
  "hero.titleHighlight": "portfolio",
  "hero.titleEnd": "in minutes",
  "hero.description": "Showcase your work with a customizable portfolio that integrates with GitHub and Figma. Stand out with beautiful templates designed for developers and designers.",
  "hero.getStarted": "Get Started",
  "hero.browseTemplates": "Browse Templates",
  "hero.usersJoined": "developers & designers joined this month",

  // Features Section
  "features.title": "Everything you need to showcase your work",
  "features.description": "Build a professional portfolio that highlights your skills and projects with powerful integrations and customization options.",
  "features.customizable.title": "Customizable Templates",
  "features.customizable.description": "Choose from a variety of professionally designed templates that you can customize to match your personal style.",
  "features.github.title": "GitHub Integration",
  "features.github.description": "Automatically import and showcase your repositories, contributions, and activity directly from GitHub.",
  "features.figma.title": "Figma Integration",
  "features.figma.description": "Connect your Figma account to display your design projects with interactive previews and prototypes.",
  "features.code.title": "Code Highlighting",
  "features.code.description": "Showcase your code snippets with syntax highlighting and interactive demos to demonstrate your skills.",
  "features.responsive.title": "Responsive Design",
  "features.responsive.description": "All portfolios are fully responsive and optimized for viewing on any device, from desktop to mobile.",
  "features.domain.title": "Custom Domain",
  "features.domain.description": "Connect your own domain name to your portfolio for a more professional and personalized web presence.",

  // Templates Showcase
  "templates.title": "Professional Templates",
  "templates.description": "Choose from our collection of beautiful, ready-to-use templates",
  "templates.viewAll": "View All Templates",
  "templates.preview": "Preview",
  "templates.useTemplate": "Use Template",

  // Testimonials Section
  "testimonials.title": "What our users say",
  "testimonials.description": "Join thousands of developers and designers who have already created their professional portfolios",
  "testimonials.1.quote": "DevFolio helped me create a stunning portfolio that showcases my work perfectly. The GitHub integration saved me hours of manual work.",
  "testimonials.1.name": "Alex Morgan",
  "testimonials.1.title": "Frontend Developer",
  "testimonials.2.quote": "As a designer, I needed a portfolio that would display my work beautifully. The Figma integration is a game-changer for showing my designs.",
  "testimonials.2.name": "Sarah Chen",
  "testimonials.2.title": "UI/UX Designer",
  "testimonials.3.quote": "I was able to set up my portfolio in under an hour. The templates are professional and the customization options are exactly what I needed.",
  "testimonials.3.name": "Michael Johnson",
  "testimonials.3.title": "Full Stack Developer",

  // CTA Section
  "cta.title": "Ready to showcase your work to the world?",
  "cta.description": "Join thousands of developers and designers who have already created their professional portfolios with DevFolio.",
  "cta.getStarted": "Get Started for Free",
  "cta.browseTemplates": "Browse Templates",

  // Templates Page
  "templatesPage.title": "Templates",
  "templatesPage.search": "Search templates...",
  "templatesPage.all": "All Templates",
  "templatesPage.developer": "Developer",
  "templatesPage.designer": "Designer",
  "templatesPage.creative": "Creative",
  "templatesPage.minimal": "Minimal",
  "templatesPage.sortBy": "Sort by:",
  "templatesPage.popular": "Popular",
  "templatesPage.newest": "Newest",
  "templatesPage.priceLow": "Price: Low to High",
  "templatesPage.priceHigh": "Price: High to Low",
  "templatesPage.noResults": "No templates found",
  "templatesPage.tryAdjusting": "Try adjusting your search or filter criteria",
  "templatesPage.free": "Free",

  // Pricing Page
  "pricing.title": "Simple, transparent pricing",
  "pricing.description": "Choose the plan that's right for you and start building your professional portfolio today",
  "pricing.monthly": "Monthly",
  "pricing.annual": "Annual (Save 20%)",
  "pricing.free.name": "Free",
  "pricing.free.description": "Perfect for getting started with your portfolio",
  "pricing.free.button": "Get Started",
  "pricing.pro.name": "Pro",
  "pricing.pro.description": "Everything you need for a professional portfolio",
  "pricing.pro.button": "Upgrade to Pro",
  "pricing.team.name": "Team",
  "pricing.team.description": "For agencies and professional teams",
  "pricing.team.button": "Contact Sales",
  "pricing.month": "/month",
  "pricing.comparePlans": "Compare Plans",
  "pricing.findPlan": "Find the plan that best fits your needs",
  "pricing.features": "Features",
  "pricing.templates": "Templates",
  "pricing.3templates": "3 templates",
  "pricing.unlimited": "Unlimited",
  "pricing.projects": "Projects",
  "pricing.upTo10": "Up to 10",
  "pricing.customDomain": "Custom Domain",
  "pricing.githubIntegration": "GitHub Integration",
  "pricing.publicRepos": "Public repos only",
  "pricing.allRepos": "All repos",
  "pricing.figmaIntegration": "Figma Integration",
  "pricing.analytics": "Analytics",
  "pricing.basic": "Basic",
  "pricing.advanced": "Advanced",
  "pricing.teamMembers": "Team Members",
  "pricing.1member": "1",
  "pricing.upTo10members": "Up to 10",
  "pricing.support": "Support",
  "pricing.email": "Email",
  "pricing.priority": "Priority",
  "pricing.dedicated": "Dedicated",
  "pricing.faq": "Frequently Asked Questions",
  "pricing.questions": "Have questions? We're here to help",

  // Login Page
  "login.title": "Welcome back",
  "login.subtitle": "Sign in to your account to continue",
  "login.email": "Email",
  "login.emailPlaceholder": "Enter your email",
  "login.password": "Password",
  "login.passwordPlaceholder": "Enter your password",
  "login.rememberMe": "Remember me",
  "login.forgotPassword": "Forgot password?",
  "login.button": "Sign In",
  "login.or": "OR CONTINUE WITH",
  "login.github": "GitHub",
  "login.google": "Google",
  "login.noAccount": "Don't have an account?",
  "login.signup": "Sign up",

  // Signup Page
  "signup.title": "Create an account",
  "signup.subtitle": "Start building your professional portfolio",
  "signup.fullName": "Full Name",
  "signup.fullNamePlaceholder": "Enter your full name",
  "signup.email": "Email",
  "signup.emailPlaceholder": "Enter your email",
  "signup.password": "Password",
  "signup.passwordPlaceholder": "Create a password",
  "signup.passwordRequirement": "Must be at least 8 characters",
  "signup.agreeTerms": "I agree to the",
  "signup.termsService": "Terms of Service",
  "signup.and": "and",
  "signup.privacyPolicy": "Privacy Policy",
  "signup.button": "Create Account",
  "signup.or": "OR CONTINUE WITH",
  "signup.github": "GitHub",
  "signup.google": "Google",
  "signup.haveAccount": "Already have an account?",
  "signup.login": "Sign in",

  // Language Switcher
  "language": "Language",
  "language.english": "English",
  "language.russian": "Русский",

  // User Menu
  "user.profile": "Profile",
  "user.settings": "Settings",
  "user.logout": "Logout",

  // Login Success
  "login.successTitle": "Login Successful",
  "login.successMessage": "You have been successfully logged in",

  // Signup Success
  "signup.successTitle": "Registration Successful",
  "signup.successMessage": "Your account has been created successfully",

  // Profile Page
  "profile.editProfile": "Edit Profile",
  "profile.projects": "Projects",
  "profile.averageRating": "Average Rating",
  "profile.views": "Profile Views",
  "profile.about": "About",
  "profile.contactInformation": "Contact Information",
  "profile.noBio": "No bio information provided.",
  "profile.noProjects": "No projects yet",
  "profile.noProjectsDescription": "Start creating your first project to showcase your work.",
  "profile.createProject": "Create Project",
  "profile.viewProject": "View Project",

  // Settings Page
  "settings.profile": "Profile",
  "settings.account": "Account",
  "settings.notifications": "Notifications",
  "settings.security": "Security",
  "settings.profileSettings": "Profile Settings",
  "settings.accountSettings": "Account Settings",
  "settings.notificationSettings": "Notification Settings",
  "settings.securitySettings": "Security Settings",
  "settings.name": "Name",
  "settings.namePlaceholder": "Enter your name",
  "settings.email": "Email",
  "settings.emailPlaceholder": "Enter your email",
  "settings.bio": "Bio",
  "settings.bioPlaceholder": "Tell us about yourself",
  "settings.location": "Location",
  "settings.locationPlaceholder": "Enter your location",
  "settings.website": "Website",
  "settings.websitePlaceholder": "Enter your website URL",
  "settings.cancel": "Cancel",
  "settings.saveChanges": "Save Changes",
  "settings.language": "Language",
  "settings.timezone": "Timezone",
  "settings.emailNotifications": "Email Notifications",
  "settings.emailNotificationsDescription": "Receive email notifications about activity on your account",
  "settings.pushNotifications": "Push Notifications",
  "settings.pushNotificationsDescription": "Receive push notifications about activity on your account",
  "settings.newsletter": "Newsletter",
  "settings.newsletterDescription": "Receive our newsletter with updates and promotions",
  "settings.projectUpdates": "Project Updates",
  "settings.projectUpdatesDescription": "Receive notifications about updates to your projects",
  "settings.changePassword": "Change Password",
  "settings.currentPassword": "Current Password",
  "settings.newPassword": "New Password",
  "settings.confirmPassword": "Confirm Password",
  "settings.updatePassword": "Update Password",
  "settings.twoFactorAuth": "Two-Factor Authentication",
  "settings.twoFactorAuthDescription": "Add an extra layer of security to your account",
  "settings.enableTwoFactor": "Enable Two-Factor Authentication",
  "settings.dangerZone": "Danger Zone",
  "settings.dangerZoneDescription": "Permanently delete your account and all of your content",
  "settings.deleteAccount": "Delete Account"
};