export const ru = {
  // Navbar
  "nav.home": "Главная",
  "nav.templates": "Шаблоны",
  "nav.pricing": "Цены",
  "nav.login": "Вход",
  "nav.signup": "Регистрация",

  // Footer
  "footer.description": "Создавайте потрясающие портфолио для разработчиков и дизайнеров с легкостью.",
  "footer.product": "Продукт",
  "footer.customers": "Клиенты",
  "footer.features": "Возможности",
  "footer.resources": "Ресурсы",
  "footer.documentation": "Документация",
  "footer.guides": "Руководства",
  "footer.apiReference": "API Справочник",
  "footer.blog": "Блог",
  "footer.company": "Компания",
  "footer.about": "О нас",
  "footer.careers": "Карьера",
  "footer.privacy": "Конфиденциальность",
  "footer.terms": "Условия",
  "footer.rights": "Все права защищены.",

  // Hero Section
  "hero.title": "Создайте свое профессиональное",
  "hero.titleHighlight": "портфолио",
  "hero.titleEnd": "за считанные минуты",
  "hero.description": "Продемонстрируйте свои работы с помощью настраиваемого портфолио, которое интегрируется с GitHub и Figma. Выделитесь с красивыми шаблонами, разработанными для разработчиков и дизайнеров.",
  "hero.getStarted": "Начать",
  "hero.browseTemplates": "Просмотреть шаблоны",
  "hero.usersJoined": "разработчиков и дизайнеров присоединились в этом месяце",

  // Features Section
  "features.title": "Всё необходимое для демонстрации ваших работ",
  "features.description": "Создайте профессиональное портфолио, которое подчеркнет ваши навыки и проекты с мощными интеграциями и возможностями настройки.",
  "features.customizable.title": "Настраиваемые шаблоны",
  "features.customizable.description": "Выбирайте из множества профессионально разработанных шаблонов, которые вы можете настроить под свой стиль.",
  "features.github.title": "Интеграция с GitHub",
  "features.github.description": "Автоматически импортируйте и демонстрируйте свои репозитории, вклады и активность прямо из GitHub.",
  "features.figma.title": "Интеграция с Figma",
  "features.figma.description": "Подключите свой аккаунт Figma для отображения ваших дизайн-проектов с интерактивными превью и прототипами.",
  "features.code.title": "Подсветка кода",
  "features.code.description": "Демонстрируйте свои фрагменты кода с подсветкой синтаксиса и интерактивными демо для демонстрации ваших навыков.",
  "features.responsive.title": "Адаптивный дизайн",
  "features.responsive.description": "Все портфолио полностью адаптивны и оптимизированы для просмотра на любом устройстве, от десктопа до мобильного.",
  "features.domain.title": "Собственный домен",
  "features.domain.description": "Подключите свое доменное имя к вашему портфолио для более профессионального и персонализированного веб-присутствия.",

  // Templates Showcase
  "templates.title": "Профессиональные шаблоны",
  "templates.description": "Выбирайте из нашей коллекции красивых, готовых к использованию шаблонов",
  "templates.viewAll": "Посмотреть все шаблоны",
  "templates.preview": "Предпросмотр",
  "templates.useTemplate": "Использовать шаблон",

  // Testimonials Section
  "testimonials.title": "Что говорят наши пользователи",
  "testimonials.description": "Присоединяйтесь к тысячам разработчиков и дизайнеров, которые уже создали свои профессиональные портфолио",
  "testimonials.1.quote": "DevFolio помог мне создать потрясающее портфолио, которое идеально демонстрирует мою работу. Интеграция с GitHub сэкономила мне часы ручной работы.",
  "testimonials.1.name": "Алекс Морган",
  "testimonials.1.title": "Frontend-разработчик",
  "testimonials.2.quote": "Как дизайнеру, мне нужно было портфолио, которое красиво отображало бы мои работы. Интеграция с Figma — это настоящий прорыв для демонстрации моих дизайнов.",
  "testimonials.2.name": "Сара Чен",
  "testimonials.2.title": "UI/UX Дизайнер",
  "testimonials.3.quote": "Я смог настроить свое портфолио менее чем за час. Шаблоны профессиональные, а возможности настройки — именно то, что мне нужно.",
  "testimonials.3.name": "Михаил Джонсон",
  "testimonials.3.title": "Full Stack разработчик",

  // CTA Section
  "cta.title": "Готовы показать свои работы миру?",
  "cta.description": "Присоединяйтесь к тысячам разработчиков и дизайнеров, которые уже создали свои профессиональные портфолио с DevFolio.",
  "cta.getStarted": "Начать бесплатно",
  "cta.browseTemplates": "Просмотреть шаблоны",

  // Templates Page
  "templatesPage.title": "Шаблоны",
  "templatesPage.search": "Поиск шаблонов...",
  "templatesPage.all": "Все шаблоны",
  "templatesPage.developer": "Разработчик",
  "templatesPage.designer": "Дизайнер",
  "templatesPage.creative": "Креативный",
  "templatesPage.minimal": "Минималистичный",
  "templatesPage.sortBy": "Сортировать по:",
  "templatesPage.popular": "Популярные",
  "templatesPage.newest": "Новые",
  "templatesPage.priceLow": "Цена: по возрастанию",
  "templatesPage.priceHigh": "Цена: по убыванию",
  "templatesPage.noResults": "Шаблоны не найдены",
  "templatesPage.tryAdjusting": "Попробуйте изменить критерии поиска или фильтрации",
  "templatesPage.free": "Бесплатно",

  // Pricing Page
  "pricing.title": "Простые, прозрачные цены",
  "pricing.description": "Выберите план, который подходит именно вам, и начните создавать свое профессиональное портфолио уже сегодня",
  "pricing.monthly": "Ежемесячно",
  "pricing.annual": "Ежегодно (Экономия 20%)",
  "pricing.free.name": "Бесплатно",
  "pricing.free.description": "Идеально для начала работы с вашим портфолио",
  "pricing.free.button": "Начать",
  "pricing.pro.name": "Про",
  "pricing.pro.description": "Всё необходимое для профессионального портфолио",
  "pricing.pro.button": "Перейти на Pro",
  "pricing.team.name": "Команда",
  "pricing.team.description": "Для агентств и профессиональных команд",
  "pricing.team.button": "Связаться с отделом продаж",
  "pricing.month": "/месяц",
  "pricing.comparePlans": "Сравнить планы",
  "pricing.findPlan": "Найдите план, который лучше всего соответствует вашим потребностям",
  "pricing.features": "Функции",
  "pricing.templates": "Шаблоны",
  "pricing.3templates": "3 шаблона",
  "pricing.unlimited": "Безлимитно",
  "pricing.projects": "Проекты",
  "pricing.upTo10": "До 10",
  "pricing.customDomain": "Собственный домен",
  "pricing.githubIntegration": "Интеграция с GitHub",
  "pricing.publicRepos": "Только публичные репозитории",
  "pricing.allRepos": "Все репозитории",
  "pricing.figmaIntegration": "Интеграция с Figma",
  "pricing.analytics": "Аналитика",
  "pricing.basic": "Базовая",
  "pricing.advanced": "Расширенная",
  "pricing.teamMembers": "Участники команды",
  "pricing.1member": "1",
  "pricing.upTo10members": "До 10",
  "pricing.support": "Поддержка",
  "pricing.email": "Email",
  "pricing.priority": "Приоритетная",
  "pricing.dedicated": "Выделенная",
  "pricing.faq": "Часто задаваемые вопросы",
  "pricing.questions": "Есть вопросы? Мы здесь, чтобы помочь",

  // Login Page
  "login.title": "С возвращением",
  "login.subtitle": "Войдите в свой аккаунт, чтобы продолжить",
  "login.email": "Email",
  "login.emailPlaceholder": "Введите ваш email",
  "login.password": "Пароль",
  "login.passwordPlaceholder": "Введите ваш пароль",
  "login.rememberMe": "Запомнить меня",
  "login.forgotPassword": "Забыли пароль?",
  "login.button": "Войти",
  "login.or": "ИЛИ ПРОДОЛЖИТЬ С",
  "login.github": "GitHub",
  "login.google": "Google",
  "login.noAccount": "Нет аккаунта?",
  "login.signup": "Зарегистрироваться",

  // Signup Page
  "signup.title": "Создать аккаунт",
  "signup.subtitle": "Начните создавать свое профессиональное портфолио",
  "signup.fullName": "Полное имя",
  "signup.fullNamePlaceholder": "Введите ваше полное имя",
  "signup.email": "Email",
  "signup.emailPlaceholder": "Введите ваш email",
  "signup.password": "Пароль",
  "signup.passwordPlaceholder": "Создайте пароль",
  "signup.passwordRequirement": "Должен содержать не менее 8 символов",
  "signup.agreeTerms": "Я согласен с",
  "signup.termsService": "Условиями использования",
  "signup.and": "и",
  "signup.privacyPolicy": "Политикой конфиденциальности",
  "signup.button": "Создать аккаунт",
  "signup.or": "ИЛИ ПРОДОЛЖИТЬ С",
  "signup.github": "GitHub",
  "signup.google": "Google",
  "signup.haveAccount": "Уже есть аккаунт?",
  "signup.login": "Войти",

  // User Menu
  "user.profile": "Профиль",
  "user.settings": "Настройки",
  "user.logout": "Выйти",

  // Login Success
  "login.successTitle": "Вход выполнен",
  "login.successMessage": "Вы успешно вошли в систему",

  // Signup Success
  "signup.successTitle": "Регистрация успешна",
  "signup.successMessage": "Ваша учетная запись успешно создана",

  // Profile Page
  "profile.editProfile": "Редактировать профиль",
  "profile.projects": "Проекты",
  "profile.averageRating": "Средний рейтинг",
  "profile.views": "Просмотры профиля",
  "profile.about": "О себе",
  "profile.contactInformation": "Контактная информация",
  "profile.noBio": "Информация о себе не указана.",
  "profile.noProjects": "Проектов пока нет",
  "profile.noProjectsDescription": "Начните создавать свой первый проект, чтобы продемонстрировать свою работу.",
  "profile.createProject": "Создать проект",
  "profile.viewProject": "Просмотреть проект",

  // Settings Page
  "settings.profile": "Профиль",
  "settings.account": "Аккаунт",
  "settings.notifications": "Уведомления",
  "settings.security": "Безопасность",
  "settings.profileSettings": "Настройки профиля",
  "settings.accountSettings": "Настройки аккаунта",
  "settings.notificationSettings": "Настройки уведомлений",
  "settings.securitySettings": "Настройки безопасности",
  "settings.name": "Имя",
  "settings.namePlaceholder": "Введите ваше имя",
  "settings.email": "Email",
  "settings.emailPlaceholder": "Введите ваш email",
  "settings.bio": "О себе",
  "settings.bioPlaceholder": "Расскажите о себе",
  "settings.location": "Местоположение",
  "settings.locationPlaceholder": "Введите ваше местоположение",
  "settings.website": "Веб-сайт",
  "settings.websitePlaceholder": "Введите URL вашего сайта",
  "settings.cancel": "Отмена",
  "settings.saveChanges": "Сохранить изменения",
  "settings.language": "Язык",
  "settings.timezone": "Часовой пояс",
  "settings.emailNotifications": "Email уведомления",
  "settings.emailNotificationsDescription": "Получать уведомления по электронной почте о действиях в вашем аккаунте",
  "settings.pushNotifications": "Push-уведомления",
  "settings.pushNotificationsDescription": "Получать push-уведомления о действиях в вашем аккаунте",
  "settings.newsletter": "Рассылка новостей",
  "settings.newsletterDescription": "Получать нашу рассылку с обновлениями и акциями",
  "settings.projectUpdates": "Обновления проектов",
  "settings.projectUpdatesDescription": "Получать уведомления об обновлениях ваших проектов",
  "settings.changePassword": "Изменить пароль",
  "settings.currentPassword": "Текущий пароль",
  "settings.newPassword": "Новый пароль",
  "settings.confirmPassword": "Подтвердите пароль",
  "settings.updatePassword": "Обновить пароль",
  "settings.twoFactorAuth": "Двухфакторная аутентификация",
  "settings.twoFactorAuthDescription": "Добавьте дополнительный уровень защиты для вашего аккаунта",
  "settings.enableTwoFactor": "Включить двухфакторную аутентификацию",
  "settings.dangerZone": "Опасная зона",
  "settings.dangerZoneDescription": "Навсегда удалить ваш аккаунт и все ваше содержимое",
  "settings.deleteAccount": "Удалить аккаунт"
};